TEMPORARY: uncomment failure workflow

diff --git a/.github/workflows/example.yaml b/.github/workflows/example.yaml
--- a/.github/workflows/example.yaml
+++ b/.github/workflows/example.yaml
@@ -45,24 +45,26 @@ jobs:
 
   # This is not useful to run all the time and fail every PR, but can be
   # uncommented to check the failing case ad-hoc.
-  # failing-job:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - run: |
-  #         echo "Failure"
-  #         exit 1
+  failing-job:
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          echo "Failure"
+          exit 1
 
-  # failing-example:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #     - id: await
-  #       uses: ./
-  #       with:
-  #         statuses: |
-  #           slow-job
-  #           success-job
-  #           failing-job
-  #     - if: ${{ failure() }}
-  #       run: |
-  #         echo '${{ steps.await.outputs.failed-statuses }}'
+  failing-example:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - id: await
+        uses: ./
+        with:
+          statuses: |
+            slow-job
+            success-job
+            failing-job
+      - if: ${{ failure() }}
+        run: |
+          echo '${{ steps.await.outputs.pending-statuses }}'
+          echo '${{ steps.await.outputs.succeeded-statuses }}'
+          echo '${{ steps.await.outputs.failed-statuses }}'
